export const sample_foods = [
    {
      id: '1',
      name: 'Pizza de pepperoni',
      cookTime: '10-20',
      price: 20000,
      favorite: false,
      origins: ['Italia'],
      stars: 4.5,
      imageUrl: 'food-1.jpg',
      tags: ['Comida rápida', 'Pizza', 'Comida chatarra'],
    },
    {
      id: '2',
      name: 'Albóndiga',
      price: 30000,
      cookTime: '20-30',
      favorite: true,
      origins: ['Persia', 'Medio Este', 'China'],
      stars: 5,
      imageUrl: 'food-2.jpg',
      tags: ['Plato fuerte', 'Comida chatarra'],
    },
    {
      id: '3',
      name: 'Hamburguesa',
      price: 15000,
      cookTime: '10-15',
      favorite: false,
      origins: ['Alemania', 'Estados unidos'],
      stars: 3.5,
      imageUrl: 'food-3.jpg',
      tags: ['Comida rápida', 'Hamburguesa', 'Comida chatarra'],
    },
    {
      id: '4',
      name: 'Papas fritas',
      price: 8000,
      cookTime: '15-20',
      favorite: true,
      origins: ['Bélgica', 'Francia'],
      stars: 3,
      imageUrl: 'food-4.jpg',
      tags: ['Comida chatarra', 'Fritos'],
    },
    {
      id: '5',
      name: 'Sopita de pollo',
      price: 18500,
      cookTime: '40-50',
      favorite: false,
      origins: ['India', 'Asia'],
      stars: 3.5,
      imageUrl: 'food-5.jpg',
      tags: ['Plato fuerte', 'Sopa'],
    },
    {
      id: '6',
      name: 'Pizza de vegetales',
      price: 17000,
      cookTime: '40-50',
      favorite: false,
      origins: ['Italia'],
      stars: 4.0,
      imageUrl: 'food-6.jpg',
      tags: ['Comida rápida', 'Pizza', 'Comida chatarra'],
    },
  ];